# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 14) do

  create_table "adjuntos", :force => true do |t|
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "db_file_id",   :integer
    t.column "ticket_id",    :integer
  end

  create_table "clientes", :force => true do |t|
    t.column "número_de_contrato",         :integer
    t.column "nombre",                      :string
    t.column "apellido_paterno",            :string
    t.column "apellido_materno",            :string
    t.column "calle",                       :string
    t.column "número_interior",            :string
    t.column "número_exterior",            :string
    t.column "colonia",                     :string
    t.column "código_postal",              :integer
    t.column "teléfono_alo",               :integer
    t.column "teléfono_telmex",            :integer
    t.column "primera_calle_de_referencia", :string
    t.column "segunda_calle_de_referencia", :string
    t.column "municipio",                   :string
    t.column "estado",                      :string
  end

  create_table "db_files", :force => true do |t|
    t.column "data", :binary
  end

  create_table "estados", :force => true do |t|
    t.column "estado", :string
  end

  create_table "historials", :force => true do |t|
    t.column "ticket_id", :integer,                                     :null => false
    t.column "dueno",     :string
    t.column "fecha",     :datetime, :default => '2008-01-02 23:37:52'
    t.column "mensaje",   :string
  end

  create_table "llamadas", :force => true do |t|
    t.column "type",                    :string
    t.column "cliente_id",              :integer
    t.column "tipo_de_llamada",         :string
    t.column "contacto",                :integer
    t.column "estado",                  :string
    t.column "fecha_y_hora",            :datetime
    t.column "agente",                  :string
    t.column "producto",                :string
    t.column "concepto_de_la_llamada",  :string
    t.column "resultado_de_la_llamada", :string
    t.column "orden",                   :string
    t.column "no_reporte",              :string
    t.column "comentarios",             :text
    t.column "fecha_de_solución",      :datetime
    t.column "paquete",                 :string
    t.column "cablepaquetes",           :string
    t.column "línea",                  :string
    t.column "soluciones",              :text
    t.column "fecha_de_instalación",   :date
    t.column "fecha_de_cobro",          :date
    t.column "digital",                 :string
  end

  add_index "llamadas", ["cliente_id"], :name => "index_llamadas_on_cliente_id"

  create_table "meta_llamadas", :force => true do |t|
    t.column "selector",      :integer
    t.column "tipo",          :string
    t.column "motivo",        :string
    t.column "razon",         :string
    t.column "resultado",     :string
    t.column "tipo_de_tipos", :string
    t.column "numeros",       :integer
    t.column "m_de_motivos",  :string
  end

  create_table "municipios", :force => true do |t|
    t.column "estado_id", :integer, :null => false
    t.column "localidad", :string
  end

  create_table "pdf_reportes", :force => true do |t|
    t.column "archivo", :binary
  end

  create_table "procesos", :force => true do |t|
    t.column "tipo_de_llamada", :string
    t.column "proceso",         :string
  end

  create_table "prospecto_cablepaquetes", :force => true do |t|
    t.column "cablepaquete", :string
  end

  create_table "prospecto_paquetes", :force => true do |t|
    t.column "servicio", :string
    t.column "paquete",  :string
  end

  create_table "roles", :force => true do |t|
    t.column "nombre", :string
  end

  create_table "tickets", :force => true do |t|
    t.column "llamada_id", :integer
    t.column "enviar_a",   :string
    t.column "dueno",      :string
    t.column "estado",     :string
    t.column "prioridad",  :string
    t.column "adjunto",    :binary
    t.column "timestamp",  :date
    t.column "abierto",    :boolean
    t.column "marcado",    :boolean
  end

  create_table "usuario_roles", :force => true do |t|
    t.column "usuario_id", :integer
    t.column "rol_id",     :integer
    t.column "created_at", :datetime
  end

  create_table "usuarios", :force => true do |t|
    t.column "nombre_de_usuario", :string
    t.column "password_salt",     :string
    t.column "password_hash",     :string
  end

end
